[package]
name = "libsgx-test-utils"
version = "0.1.0"
authors = ["cipepser <respepic@gmail.com>"]
edition = "2018"

[dependencies]
inventory = { rev = "sgx_1.1.2", git = "https://github.com/mesalock-linux/inventory-sgx"}
serde = { rev = "sgx_1.1.2", git = "https://github.com/mesalock-linux/serde-sgx.git", features = ["derive"] }
sgx_tstd = { rev = "v1.1.2", git = "https://github.com/apache/teaclave-sgx-sdk.git", features = ["net"] }
test-utils-proc-macro = { path = "./proc-macro" }
